[[plugins]]
package = "@netlify/plugin-nextjs"

[build]
publish = ".next"

[[redirects]]
  from = "/api/*"
  to = "https://v2.gpadcrew.com/:splat"
  status = 200
  force = true

[context.develop]
  environment = { NODE_ENV = "staging" }