[[redirects]]
  from = "/api/*"
  to = "https://v2.gpadcrew.com/:splat"
  force = true
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build]
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://gpadcrew.com/api"
  NEXT_PUBLIC_ASSETS = "https://i.gpadcrew.com"

[context.develop.environment]
  NODE_ENV = "staging"
  NEXT_PUBLIC_API_URL = "https://develop.gpadcrew.com/api"
  NEXT_PUBLIC_ASSETS = "https://i.gpadcrew.com"